export const routePaths = {
  home: '/',
  login: '/login',
  register: '/register',
  profile: '/profile',
  catalog: '/catalog',
  productDetails: '/catalog/:id',
  catalogDetails: (id: string) => `/catalog/${id}`,
  atelier: '/atelier-ai',
  myCustomProducts: '/mis-cotizaciones',
  customProductDetailPattern: '/mis-cotizaciones/:id',
  customProductDetail: (id: string) => `/mis-cotizaciones/${id}`,
  myOrders: '/mis-pedidos',
  basket: '/basket',
  support: '/support',
  supportTicket: '/support/:id',
  supportTicketDetail: (id: string) => `/support/${id}`,
  checkout: '/checkout',
  checkoutSuccess: '/checkout/success',
  notFound: '/not-found',
  serverError: '/server-error',
} as const;